Update Drools results for 7.73.0.Final.
dmn-tck/tck pull request #519
Opened 2022-10-05 12:23 UTC by baldimir

2022-10-05 12:33 UTC, tarilabs requested changes
You definitely need to maintain a vendor supplied property attributes. See details below.

I believe if you just run the runner on version bump (without deleting files first), it would maintain the properties at the new version. IIRC.

2022-10-05 12:33 UTC, tarilabs commented on TestResults/Drools/7.73.0.Final/tck_results.properties
> +product.version=7.73.0.Final
```suggestion
product.version=7.73.0.Final
product.url=http\://www.drools.org
vendor.url=http\://www.redhat.com
product.comment=Drools provides a compliance level 3 runtime DMN engine
vendor.name=Red Hat
instructions.url=https\://github.com/dmn-tck/tck/tree/master/runners/dmn-tck-runner-drools/README.md
product.name=Drools
```

2022-10-05 13:05 UTC, baldimir commented
Thank you for the suggestion.

2022-10-20 07:13 UTC, baldimir commented
@tarilabs Is it ok now please? Can I merge?

2022-10-20 07:32 UTC, tarilabs approved these changes
I do believe 7b00e4f implemented the required changes, yes

2022-10-20 11:29 UTC, merged